theme: "minimal-mistakes-jekyll"
title: "Your Portfolio"
description: "Your description goes here."
url: "https://username.github.io"  # Replace with your GitHub username
author:
  name: "Your Name"
  email: "your-email@example.com"
  url: "https://yourwebsite.com"  # Optional
